# Generated by Django 5.0 on 2023-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Статья'), ('news', 'Новость')], default='post', max_length=10),
        ),
    ]
